# Dependencies
markdown:         Kramdown
highlighter:      rouge

# Theme
theme:            no-style-please

# Theme configuration
theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: "home" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how dates are formatted
  show_description: true # show blog description in home page

# Permalinks
permalink:        pretty

# Setup
title:            Aqib Gatoo
tagline:          'Portfolio/Blog'
description:      'Senior Software Engineer'
url:              http://iamaqib.xyz
baseurl:         /

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

author:
  name:           'Aqib Gatoo'
  url:            https://twitter.com/aqibgatooo

paginate:         3
