# Dependencies
markdown:         Kramdown
# pygments:         true
highlighter: pygments
# Permalinks
permalink:        pretty

# Setup
title:            Aqib Gatoo
tagline:          'Portfolio/Blog'
description:      'Full Stack Dev'
url:              http://iamaqib.xyz
baseurl:         /

gems:
  - jekyll-sitemap

author:
  name:           'Aqib Gatoo'
  url:            https://twitter.com/aqibgatooo

paginate:         3
